# Generated by Django 4.2.7 on 2023-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SL', 'Sleeves'), ('TS', 'Shirts'), ('SS', 'Shorts'), ('JT', 'Jackets')], max_length=2),
        ),
    ]
