# Generated by Django 4.2.7 on 2023-11-26 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPlaced',
            new_name='Order',
        ),
    ]
