# Generated by Django 4.2.7 on 2023-11-26 09:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_rename_orderplaced_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderPlaced',
        ),
    ]
